version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    networks:
      - mongo-network
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017
    networks:
      - mongo-network
    ports:
      - "8082:8081"

  app-cont:
    image: app_deploy_image
    networks:
      - mongo-network
    ports:
      - "5050:5050"

networks:
  mongo-network:
    external: true